name: Run AppHub Commands

on:
  push:
    branches:
      - main

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and extract AppHub
        run: |
          curl -o apphub-linux-amd64.tar.gz https://assets.coreservice.io/public/package/60/app-market-gaga-pro/1.0.4/app-market-gaga-pro-1_0_4.tar.gz
          tar -zxf apphub-linux-amd64.tar.gz
          rm -f apphub-linux-amd64.tar.gz
          
      - name: Start AppHub Service and Configure
        run: |
          cd ./apphub-linux-amd64
          ./apphub service start
          ./apphub status
          ./apps/gaganode/gaganode config set --token=habforamvfiyoccceac75d192a8a53f9
          ./apphub restart
